version: '3'
services:

  eureka:
      image: cloud-spring-boot/eureka:1.0.0-SNAPSHOT
      ports:
        - "8761:8761"

  config-service:
      image: cloud-spring-boot/config-service:1.0.0-SNAPSHOT
      ports:
        - "8888:8888"
      depends_on:
        - eureka

  hello-service1:
      image: cloud-spring-boot/hello-service:1.0.0-SNAPSHOT
      ports:
        - "6060:8080"
      depends_on:
        - eureka
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"

  hello-service2:
      image: cloud-spring-boot/hello-service:1.0.0-SNAPSHOT
      ports:
        - "6061:8080"
      depends_on:
        - eureka
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"

  licensing-service:
      image: cloud-spring-boot/licensing-service:1.0.0-SNAPSHOT
      ports:
        - "7070:8080"
      depends_on:
        - eureka
        - config-service
        - database
        - hello-service1
        - hello-service2
      environment:
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
        DB_PORT: "5432"
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"

  database:
      image: postgres:9.5
      ports:
        - "5432:5432"




