version: '2.1'
services:

  zipkin:
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT: "8888"

  config-service:
    environment:
      ENCRYPT_KEY: "prod-password"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  zuul:
    environment:
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT:   "8888"

  auth:
    environment:
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT:   "8888"

  licensing-service:
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT:   "8888"
      DB_PORT: "5432"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      AUTH_URI: "http://auth:3333/auth/user"
      KAFKA_SERVER_URI: "kafka"
      ZK_SERVER_URI: "kafka"
      KAFKA_SERVER_PORT: "2181"
      ZIPKIN_SERVER_URI: "http://zipkin:9411"

  database:
    environment:
      POSTGRES_USER: "postgres_prod"
      POSTGRES_PASSWORD: "611191"
      POSTGRES_DB: "eagle_eye_prod"

  organization-service1:
      environment:
        PROFILE: "prod"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        AUTH_URI: "http://auth:3333/auth/user"
        KAFKA_SERVER_URI: "kafka"
        ZK_SERVER_URI: "kafka"
        KAFKA_SERVER_PORT: "2181"
        ZIPKIN_SERVER_URI: "http://zipkin:9411"

#  organization-service2:
#      environment:
#        PROFILE: "prod"
#        CONFIGSERVER_URI: "http://config-service:8888"
#        CONFIGSERVER_PORT:   "8888"
#        EUREKASERVER_URI: "http://eureka:8761/eureka/"
#        EUREKASERVER_PORT: "8761"
#        AUTH_URI: "http://auth:3333/auth/user"
