version: '2.1'
services:

  eureka:
      image: cloud-spring-boot/eureka:1.0.0-SNAPSHOT
      ports:
        - "8761:8761"
      mem_limit: 1g

  config-service:
      image: cloud-spring-boot/config-service:1.0.0-SNAPSHOT
      ports:
        - "8888:8888"
      depends_on:
        - eureka
      mem_limit: 1g

  zuul:
      image: cloud-spring-boot/zuul:1.0.0-SNAPSHOT
      ports:
        - "5555:5555"
      depends_on:
        - eureka
        - config-service
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
      mem_limit: 1g

  licensing-service:
      image: cloud-spring-boot/licensing-service:1.0.0-SNAPSHOT
      ports:
        - "7070:8080"
      depends_on:
        - eureka
        - config-service
        - database
        - organization-service1
        - organization-service2
      environment:
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
        DB_PORT: "5432"
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
      mem_limit: 2g

  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      mem_limit: 1g
      memswap_limit: 1g

  organization-service1:
      image: cloud-spring-boot/organization-service:1.0.0-SNAPSHOT
      ports:
        - "6062:8080"
      depends_on:
        - eureka
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
      mem_limit: 1g
      memswap_limit: 1g

  organization-service2:
      image: cloud-spring-boot/organization-service:1.0.0-SNAPSHOT
      ports:
        - "6063:8080"
      depends_on:
        - eureka
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
      mem_limit: 1g
      memswap_limit: 1g

#  correlation-service1:
#      image: cloud-spring-boot/correlation-service:1.0.0-SNAPSHOT
#      ports:
#        - "6060:8080"
#      depends_on:
#        - eureka
#      environment:
#        EUREKASERVER_URI: "http://eureka:8761/eureka/"
#        EUREKASERVER_PORT: "8761"
#      mem_limit: 1g



