version: '2.1'
services:

  config-service:
    environment:
      ENCRYPT_KEY: "dev-password"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  zuul:
    environment:
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT:   "8888"

  licensing-service:
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT:   "8888"
      DB_PORT: "5432"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      AUTH_URI: "http://auth:3333/auth/user"

  database:
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "611191"
      POSTGRES_DB: "eagle_eye_dev"


