version: '2.1'
services:

  eureka:
      image: cloud-spring-boot/eureka:1.0.0-SNAPSHOT
      ports:
        - "8761:8761"
      volumes:
        - ./pcap:/usr/local/eureka/pcap/
      mem_limit: 1g

  config-service:
      image: cloud-spring-boot/config-service:1.0.0-SNAPSHOT
      ports:
        - "8888:8888"
      depends_on:
        - eureka
      volumes:
        - ./pcap:/usr/local/config-service/pcap
      mem_limit: 1g

  zuul:
      image: cloud-spring-boot/zuul:1.0.0-SNAPSHOT
      ports:
        - "5555:5555"
      depends_on:
        - eureka
        - config-service
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
      volumes:
        - ./pcap:/usr/local/zuul/pcap/
      mem_limit: 1g

  auth:
      image: cloud-spring-boot/auth:1.0.0-SNAPSHOT
      ports:
        - "3333:3333"
      depends_on:
        - eureka
        - config-service
      environment:
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
      volumes:
        - ./pcap:/usr/local/auth/pcap/
      mem_limit: 1g

  licensing-service:
      image: cloud-spring-boot/licensing-service:1.0.0-SNAPSHOT
      ports:
        - "7070:8080"
      depends_on:
        - eureka
        - config-service
        - database
        - redis
        - organization-service1
#        - organization-service2
        - kafka
      environment:
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
        DB_PORT: "5432"
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        AUTH_URI: "http://auth:3333/auth/user"
        KAFKA_SERVER_URI: "kafka"
        ZK_SERVER_URI: "kafka"
        KAFKA_SERVER_PORT: "2181"
      volumes:
        - ./pcap:/usr/local/licensing-service/pcap/
      mem_limit: 2g

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    mem_limit: 256m

  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      mem_limit: 1g
      memswap_limit: 1g

  organization-service1:
      image: cloud-spring-boot/organization-service:1.0.0-SNAPSHOT
      ports:
        - "6062:8080"
      depends_on:
        - eureka
        - kafka
      environment:
        PROFILE: "default"
        CONFIGSERVER_URI: "http://config-service:8888"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        AUTH_URI: "http://auth:3333/auth/user"
        KAFKA_SERVER_URI: "kafka"
        ZK_SERVER_URI: "kafka"
        KAFKA_SERVER_PORT: "2181"
      volumes:
        - ./pcap:/usr/local/organization-service/pcap/
      mem_limit: 1g
      memswap_limit: 1g

#  organization-service2:
#      image: cloud-spring-boot/organization-service:1.0.0-SNAPSHOT
#      ports:
#        - "6063:8080"
#      depends_on:
#        - eureka
#      environment:
#        PROFILE: "default"
#        CONFIGSERVER_URI: "http://config-service:8888"
#        CONFIGSERVER_PORT:   "8888"
#        EUREKASERVER_URI: "http://eureka:8761/eureka/"
#        EUREKASERVER_PORT: "8761"
#        AUTH_URI: "http://auth:3333/auth/user"
#      volumes:
#        - ./pcap:/usr/local/organization-service/pcap/
#      mem_limit: 1g
#      memswap_limit: 1g

  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    mem_limit: 512m
