version: '2'
services:
  config-service:
      extends:
        file: ../docker-compose.yml
        service: config-service
      environment:
        ENCRYPT_KEY: "dev-password"

  hello-service:
      extends:
        file: ../docker-compose.yml
        service: hello-service

  licensing-service:
        extends:
            file: ../docker-compose.yml
            service: licensing-service
        environment:
          PROFILE: "dev"
          CONFIGSERVER_URI: "http://config-service:8888"
          CONFIGSERVER_PORT:   "8888"
          DB_PORT: "5432"

  database:
    extends:
      file: ../docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "611191"
      POSTGRES_DB: "eagle_eye_dev"
