version: '2'
services:
  config-service:
      extends:
        file: ../docker-compose.yml
        service: config-service
      environment:
        ENCRYPT_KEY: "dev-password"

  hello-service:
      extends:
        file: ../docker-compose.yml
        service: hello-service

  licensing-service:
        extends:
            file: ../docker-compose.yml
            service: licensing-service
        environment:
          PROFILE: "dev"
          CONFIGSERVER_URI: "http://config-service:8888"
          CONFIGSERVER_PORT:   "8888"
