version: '2.1'
services:

  eureka:
    extends:
      file: ../docker-compose.yml
      service: eureka

  config-service:
    extends:
      file: ../docker-compose.yml
      service: config-service
    depends_on:
      - eureka
    environment:
      ENCRYPT_KEY: "dev-password"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  hello-service1:
    extends:
      file: ../docker-compose.yml
      service: hello-service1
    depends_on:
      - eureka
    environment:
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  hello-service2:
    extends:
      file: ../docker-compose.yml
      service: hello-service2
    depends_on:
      - eureka
    environment:
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  licensing-service:
    extends:
      file: ../docker-compose.yml
      service: licensing-service
    depends_on:
      - eureka
      - config-service
      - database
      - hello-service1
      - hello-service2
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT:   "8888"
      DB_PORT: "5432"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  database:
    extends:
      file: ../docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "611191"
      POSTGRES_DB: "eagle_eye_dev"


